### PR TITLE
Sections

### LINKED ISSUE #9: Make page for adding class and sections
- [ ] Make an entry on homepage for "Classes"
- [ ] add classes as default

### PR DESCRIPTION
**Pull request by taimur38**
should close #9 if approved by ayesha

### CODE REVIEW

**Comment by Ayesha19** [comment]
Overall everything looks good, just some issues:
1) Pressing the 'save' button do not give any notification which can confirm the user that its saved.
2) Would the user be able to edit the name of subject (as in spelling)?
3) Can MIS save any new subject added in the dropdown list ?
4) Creating a new class 'Class 1-A' is editing the  'Class 2 -A'!!

**Comment by Ayesha19** [comment]
Some changes needed in teacher's profile:
1) Pressing 'save' in teacher's module is not giving notification.
2) Limit numbers in CNIC (13 numbers) and phone number (11 number max) . Also can the hyphen '-' be added automatically in CNIC??
3) Qualification field is not in teacher's profile.
4) There's no husband or father's name field.
5) Rename 'birth date' to 'date of birth'.

**Comment by Ayesha19** [comment]
Modifications for student's profile:
1) Rename CNIC with 'B-form number'.
2) Rename 'section' as 'Class'
3) Rename 'Birth date' to ' Date of Birth'
4) Add scholarship type and scholarship amount so that it can be automatically be subtracted in fees module.
5) Schools wanted to have a family id for all the siblings or cousins which can be used as a filter in fees module. 
6) There's no father's name field .

**Comment by Ayesha19** [comment]
Feedback about classes module:
1) We need to have more subjects in that list such as:
English (rename literature), Urdu, Islamiat, Pak-studies
2) Add subject layout is misleading as in the user dont get the idea that theres a dropdown option for selecting subject. even I pressed add subject without selecting any subject in the first box.
Suggestion:  atleast write something in that blank like 'select a subject'.
3) Box for section name already has a new section name written there and the user have to erase it first and then write anything.
image

**Comment by taimur38** [comment]
Addressed all but fee-related questions. Delete will come next week

**Pull request merged**
